=== AlexandreVaughan/easymol/src/fr/emn/easymol/xml/molecule.dtd
<!ELEMENT compound (molecule+)>
<!ELEMENT molecule (#PCDATA|molecule|atom)*>
<!ATTLIST molecule name CDATA #REQUIRED
				   formula CDATA #IMPLIED>
				  
<!ELEMENT atom (#PCDATA|bond)*>
<!ATTLIST atom name CDATA #REQUIRED
			   bondid ID #IMPLIED>
<!ELEMENT bond EMPTY>
<!ATTLIST bond id IDREF #REQUIRED
				  valency NMTOKENS #REQUIRED>

=== AlexandreVaughan/easymol/bin/fr/emn/easymol/xml/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	A sample water molecule.
-->
<!DOCTYPE compound SYSTEM "molecule.dtd">
<compound>
<molecule name="H2O">
	<atom name="H" bondid="h1" >
		<bond id="O" valency="1" />
	</atom>
	<atom name="H" bondid="h2">
		<bond id="O" valency="1" />
	</atom>
	<atom name="O" bondid="O">
		<bond id="h1" valency="1" />
		<bond id="h2" valency="1" />
	</atom>
</molecule>
</compound>
